# Setup
title:        A-Town at the Movies
tagline:      A film podcast by the creators of A-Town FM
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Author name
  url:        http://yourhomepage.com 

# Gems
plugins:
  - jekyll-paginate

#Others
markdown: kramdown
fbcomments: yes